apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: datablock clone
  annotations:
    github.com/project-slug: npiyush97/datablock-clone
spec:
  type: other
  lifecycle: unknown
  owner: acme-corp
